import {
  CONCIERGE_SCHEMA_VERSION,
  type ConciergeCondition,
  type ConciergeDefinition,
  type ConciergeFlowDefinition,
  type ConciergeNextStep,
  type ConciergePath,
  type ConciergeQuestion,
  type ConciergeQuestionOption,
  type ConciergeQuestionPath,
  type ConciergeStep,
  type ConciergeSystemStep,
} from './types'

type QuestionInput = Omit<
  ConciergeQuestion,
  'kind' | 'allowsFreeText' | 'sensitiveData'
> &
  Partial<Pick<ConciergeQuestion, 'allowsFreeText' | 'sensitiveData'>>

function defineQuestion(input: QuestionInput): ConciergeQuestion {
  return {
    kind: 'question',
    allowsFreeText: false,
    sensitiveData: false,
    ...input,
  }
}

function defineSystemStep(
  input: Omit<ConciergeSystemStep, 'kind'>,
): ConciergeSystemStep {
  return { kind: 'system', ...input }
}

function options(values: readonly string[]): readonly ConciergeQuestionOption[] {
  return values.map((value) => ({ value, label: value }))
}

function categoryCondition(value: string): ConciergeCondition {
  return {
    questionId: 'solutions.need_category',
    operator: 'equals',
    value,
  }
}

const currentProspectingOptions = options([
  'Aucune prospection structurée',
  'Recommandations et réseau',
  'Email',
  'Téléphone',
  'LinkedIn',
  'Publicité',
  'Équipe commerciale interne',
  'Prestataire externe',
  'Plusieurs canaux',
  'Autre',
])

const mainDifficultyOptions = options([
  'Définir la bonne cible',
  'Trouver suffisamment d’entreprises',
  'Identifier les décideurs',
  'Personnaliser les approches',
  'Obtenir des réponses',
  'Qualifier les demandes',
  'Organiser le suivi',
  'Manque de temps',
  'Manque de ressources internes',
  'Autre',
])

const indicativeBudgetOptions = options([
  'À définir après cadrage',
  'Moins de 5 000 €',
  'De 5 000 € à 15 000 €',
  'De 15 000 € à 50 000 €',
  'Plus de 50 000 €',
])

const solutionCategoryOptions = [
  {
    value: 'website_seo_geo',
    label: 'Site web, SEO et GEO',
  },
  {
    value: 'business_software',
    label: 'Logiciel métier',
  },
  {
    value: 'web_app_integration',
    label: 'Application, intégration ou automatisation',
  },
  {
    value: 'local_ai',
    label: 'Intelligence artificielle locale',
  },
  {
    value: 'ai_infrastructure',
    label: 'Station ou serveur IA',
  },
  {
    value: 'backup_continuity',
    label: 'Sauvegarde et continuité',
  },
  {
    value: 'cybersecurity_authorized_audit',
    label: 'Cybersécurité et audit autorisé',
  },
  { value: 'other', label: 'Autre besoin' },
] as const satisfies readonly ConciergeQuestionOption[]

export const sharedConciergeSteps = [
  defineSystemStep({
    id: 'summary.review',
    path: 'shared',
    section: 'summary',
    stepType: 'summary',
    nextStep: 'contact.full_name',
  }),
  defineQuestion({
    id: 'contact.full_name',
    path: 'shared',
    section: 'contact',
    label: 'Nom complet',
    prompt: 'À quel nom Novekia peut-il rattacher cette demande ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 120 },
    nextStep: 'contact.company',
    sensitiveData: true,
    sensitiveDataJustification:
      'Nécessaire pour identifier la personne qui demande à être recontactée.',
  }),
  defineQuestion({
    id: 'contact.company',
    path: 'shared',
    section: 'contact',
    label: 'Entreprise',
    prompt: 'Pour quelle entreprise préparez-vous cette demande ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 160 },
    nextStep: 'contact.role',
  }),
  defineQuestion({
    id: 'contact.role',
    path: 'shared',
    section: 'contact',
    label: 'Fonction',
    prompt: 'Quelle est votre fonction dans l’entreprise ?',
    answerType: 'short_text',
    required: false,
    validation: { maxLength: 120 },
    nextStep: 'contact.email',
  }),
  defineQuestion({
    id: 'contact.email',
    path: 'shared',
    section: 'contact',
    label: 'E-mail professionnel',
    prompt: 'À quelle adresse professionnelle pouvons-nous vous répondre ?',
    answerType: 'email',
    required: true,
    validation: {
      format: 'email',
      maxLength: 254,
      customRule: 'professional_email_preferred',
    },
    nextStep: 'contact.phone',
    sensitiveData: true,
    sensitiveDataJustification:
      'Nécessaire pour répondre à la demande de contact initiée par le visiteur.',
  }),
  defineQuestion({
    id: 'contact.phone',
    path: 'shared',
    section: 'contact',
    label: 'Téléphone',
    prompt: 'Souhaitez-vous laisser un numéro de téléphone ?',
    answerType: 'phone',
    required: false,
    validation: { format: 'phone', maxLength: 40 },
    nextStep: 'contact.preferred_contact',
    sensitiveData: true,
  }),
  defineQuestion({
    id: 'contact.preferred_contact',
    path: 'shared',
    section: 'contact',
    label: 'Préférence de contact',
    prompt: 'Comment préférez-vous être recontacté ?',
    answerType: 'single_choice',
    required: false,
    options: [
      { value: 'email', label: 'E-mail' },
      { value: 'phone', label: 'Téléphone' },
      { value: 'either', label: 'E-mail ou téléphone' },
    ],
    nextStep: 'consent.contact',
  }),
  defineQuestion({
    id: 'consent.contact',
    path: 'shared',
    section: 'consent',
    label: 'Consentement de contact',
    prompt:
      'J’accepte que Novekia utilise les informations fournies afin de me recontacter au sujet de ma demande.',
    answerType: 'consent',
    required: true,
    validation: { customRule: 'explicit_consent_required' },
    nextStep: 'consent.privacy',
    sensitiveData: true,
    sensitiveDataJustification:
      'Preuve explicite et datée de l’accord de contact du visiteur.',
  }),
  defineQuestion({
    id: 'consent.privacy',
    path: 'shared',
    section: 'consent',
    label: 'Politique de confidentialité',
    prompt:
      'Je reconnais avoir pris connaissance de la politique de confidentialité de Novekia.',
    answerType: 'consent',
    required: true,
    validation: { customRule: 'explicit_consent_required' },
    nextStep: 'submission.ready',
    sensitiveData: true,
    sensitiveDataJustification:
      'Preuve explicite et datée de la prise de connaissance de la politique.',
  }),
  defineSystemStep({
    id: 'submission.ready',
    path: 'shared',
    section: 'submission',
    stepType: 'ready_to_submit',
    nextStep: null,
  }),
] as const satisfies readonly ConciergeStep[]

const leadEngineSteps = [
  defineQuestion({
    id: 'lead.company_name',
    path: 'lead_engine',
    section: 'context',
    label: 'Nom de l’entreprise',
    prompt: 'Quelle entreprise souhaitez-vous développer ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 160 },
    nextStep: 'lead.company_website',
  }),
  defineQuestion({
    id: 'lead.company_website',
    path: 'lead_engine',
    section: 'context',
    label: 'Site internet',
    prompt: 'Quel est le site internet de l’entreprise ?',
    helpText: 'Facultatif : son absence ne disqualifie pas la demande.',
    answerType: 'url',
    required: false,
    validation: { format: 'url', maxLength: 300 },
    nextStep: 'lead.sector',
  }),
  defineQuestion({
    id: 'lead.sector',
    path: 'lead_engine',
    section: 'context',
    label: 'Secteur d’activité',
    prompt: 'Dans quel secteur l’entreprise opère-t-elle ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 160 },
    nextStep: 'lead.offer',
  }),
  defineQuestion({
    id: 'lead.offer',
    path: 'lead_engine',
    section: 'context',
    label: 'Offre principale',
    prompt: 'Quelle offre souhaitez-vous principalement commercialiser ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 10, maxLength: 1200 },
    nextStep: 'lead.respondent_role',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'lead.respondent_role',
    path: 'lead_engine',
    section: 'context',
    label: 'Votre fonction',
    prompt: 'Quelle est votre fonction dans l’entreprise ?',
    answerType: 'short_text',
    required: false,
    validation: { maxLength: 120 },
    nextStep: 'lead.target_customer',
  }),
  defineQuestion({
    id: 'lead.target_customer',
    path: 'lead_engine',
    section: 'target',
    label: 'Clients recherchés',
    prompt: 'Quels types de clients recherchez-vous ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1000 },
    nextStep: 'lead.target_company_profile',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'lead.target_company_profile',
    path: 'lead_engine',
    section: 'target',
    label: 'Profil des entreprises ciblées',
    prompt: 'Quelle taille ou quel profil d’entreprise ciblez-vous ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 300 },
    nextStep: 'lead.target_geography',
  }),
  defineQuestion({
    id: 'lead.target_geography',
    path: 'lead_engine',
    section: 'target',
    label: 'Zone géographique',
    prompt: 'Sur quelles zones géographiques souhaitez-vous prospecter ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 300 },
    nextStep: 'lead.target_roles',
  }),
  defineQuestion({
    id: 'lead.target_roles',
    path: 'lead_engine',
    section: 'target',
    label: 'Interlocuteurs visés',
    prompt: 'Quelles fonctions ou quels décideurs visez-vous généralement ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 400 },
    nextStep: 'lead.current_prospecting',
  }),
  defineQuestion({
    id: 'lead.current_prospecting',
    path: 'lead_engine',
    section: 'current_prospecting',
    label: 'Prospection actuelle',
    prompt: 'Comment prospectez-vous actuellement ?',
    answerType: 'multiple_choice',
    required: true,
    options: currentProspectingOptions,
    validation: {
      allowedValues: currentProspectingOptions.map((item) => item.value),
    },
    nextStep: 'lead.sales_team',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'lead.sales_team',
    path: 'lead_engine',
    section: 'current_prospecting',
    label: 'Équipe commerciale',
    prompt: 'Disposez-vous d’une équipe commerciale ?',
    answerType: 'single_choice',
    required: true,
    options: options([
      'Aucune équipe dédiée',
      'Une personne',
      'Deux à cinq personnes',
      'Plus de cinq personnes',
      'Organisation mixte ou externe',
    ]),
    nextStep: 'lead.crm_tools',
  }),
  defineQuestion({
    id: 'lead.crm_tools',
    path: 'lead_engine',
    section: 'current_prospecting',
    label: 'Outils ou CRM',
    prompt: 'Quels outils ou CRM utilisez-vous aujourd’hui ?',
    answerType: 'short_text',
    required: false,
    validation: { maxLength: 500 },
    nextStep: 'lead.current_volume',
  }),
  defineQuestion({
    id: 'lead.current_volume',
    path: 'lead_engine',
    section: 'current_prospecting',
    label: 'Volume actuel',
    prompt: 'Quel volume approximatif traitez-vous actuellement chaque mois ?',
    answerType: 'short_text',
    required: false,
    validation: { maxLength: 200 },
    nextStep: 'lead.main_objective',
  }),
  defineQuestion({
    id: 'lead.main_objective',
    path: 'lead_engine',
    section: 'objective',
    label: 'Objectif commercial',
    prompt: 'Quel est votre objectif commercial principal ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1000 },
    nextStep: 'lead.monthly_objective',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'lead.monthly_objective',
    path: 'lead_engine',
    section: 'objective',
    label: 'Objectif mensuel',
    prompt: 'Quel volume mensuel souhaiteriez-vous viser ?',
    helpText:
      'Il s’agit d’un objectif de cadrage, jamais d’une promesse de résultat.',
    answerType: 'number',
    required: false,
    validation: { min: 0, max: 100000, format: 'integer' },
    nextStep: 'lead.main_difficulty',
  }),
  defineQuestion({
    id: 'lead.main_difficulty',
    path: 'lead_engine',
    section: 'objective',
    label: 'Difficulté principale',
    prompt: 'Quelle est aujourd’hui votre principale difficulté ?',
    answerType: 'single_choice',
    required: true,
    options: mainDifficultyOptions,
    validation: {
      allowedValues: mainDifficultyOptions.map((item) => item.value),
    },
    nextStep: 'lead.timeframe',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'lead.timeframe',
    path: 'lead_engine',
    section: 'objective',
    label: 'Délai souhaité',
    prompt: 'Quand souhaiteriez-vous commencer ?',
    answerType: 'single_choice',
    required: true,
    options: options([
      'Dès que le cadrage est validé',
      'Sous un mois',
      'Sous trois mois',
      'Plus tard',
      'À définir',
    ]),
    nextStep: 'lead.regulatory_constraints',
  }),
  defineQuestion({
    id: 'lead.regulatory_constraints',
    path: 'lead_engine',
    section: 'constraints',
    label: 'Contraintes réglementaires',
    prompt: 'Existe-t-il des contraintes réglementaires ou sectorielles ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'lead.refused_channels',
    allowsFreeText: true,
    humanReviewTrigger: {
      reason: 'Une contrainte réglementaire déclarée doit être examinée.',
      severity: 'review',
      condition: {
        questionId: 'lead.regulatory_constraints',
        operator: 'exists',
      },
    },
  }),
  defineQuestion({
    id: 'lead.refused_channels',
    path: 'lead_engine',
    section: 'constraints',
    label: 'Canaux non souhaités',
    prompt: 'Quels canaux refusez-vous ou ne souhaitez-vous pas utiliser ?',
    answerType: 'multiple_choice',
    required: true,
    options: options([
      'Aucun',
      'Email',
      'Téléphone',
      'LinkedIn',
      'Publicité',
      'Autre',
    ]),
    nextStep: 'lead.human_review_points',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'lead.human_review_points',
    path: 'lead_engine',
    section: 'constraints',
    label: 'Points à valider humainement',
    prompt: 'Quels points nécessitent selon vous une validation humaine ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'lead.indicative_budget',
    allowsFreeText: true,
    humanReviewTrigger: {
      reason: 'Le visiteur a explicitement demandé une validation humaine.',
      severity: 'review',
      condition: {
        questionId: 'lead.human_review_points',
        operator: 'exists',
      },
    },
  }),
  defineQuestion({
    id: 'lead.indicative_budget',
    path: 'lead_engine',
    section: 'constraints',
    label: 'Enveloppe indicative',
    prompt: 'Souhaitez-vous indiquer une enveloppe de travail ?',
    helpText:
      'Facultatif et demandé uniquement en fin de cadrage ; ce n’est pas un tarif.',
    answerType: 'single_choice',
    required: false,
    options: indicativeBudgetOptions,
    nextStep: 'summary.review',
  }),
] as const satisfies readonly ConciergeStep[]

const solutionBranchEntry: ConciergeNextStep = {
  branches: solutionCategoryOptions.map((category) => ({
    condition: categoryCondition(category.value),
    stepId: `solutions.${category.value}.start`,
  })),
  defaultStepId: 'summary.review',
}

const solutionCommonSteps = [
  defineQuestion({
    id: 'solutions.company_name',
    path: 'solutions',
    section: 'context',
    label: 'Nom de l’entreprise',
    prompt: 'Pour quelle entreprise préparez-vous ce projet ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 160 },
    nextStep: 'solutions.company_website',
  }),
  defineQuestion({
    id: 'solutions.company_website',
    path: 'solutions',
    section: 'context',
    label: 'Site internet',
    prompt: 'Quel est le site actuel de l’entreprise ?',
    helpText: 'Facultatif : son absence ne disqualifie pas le projet.',
    answerType: 'url',
    required: false,
    validation: { format: 'url', maxLength: 300 },
    nextStep: 'solutions.sector',
  }),
  defineQuestion({
    id: 'solutions.sector',
    path: 'solutions',
    section: 'context',
    label: 'Secteur',
    prompt: 'Dans quel secteur évolue l’entreprise ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 160 },
    nextStep: 'solutions.need_category',
  }),
  defineQuestion({
    id: 'solutions.need_category',
    path: 'solutions',
    section: 'context',
    label: 'Catégorie du besoin',
    prompt: 'Quelle catégorie correspond le mieux à votre besoin ?',
    answerType: 'single_choice',
    required: true,
    options: solutionCategoryOptions,
    validation: {
      allowedValues: solutionCategoryOptions.map((item) => item.value),
    },
    nextStep: 'solutions.project_description',
  }),
  defineQuestion({
    id: 'solutions.project_description',
    path: 'solutions',
    section: 'context',
    label: 'Problème ou objectif',
    prompt: 'Quel problème souhaitez-vous résoudre ou quel objectif visez-vous ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 20, maxLength: 2000 },
    nextStep: 'solutions.current_state',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'solutions.current_state',
    path: 'solutions',
    section: 'context',
    label: 'Situation actuelle',
    prompt: 'Comment ce besoin est-il traité aujourd’hui ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1500 },
    nextStep: 'solutions.expected_users',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'solutions.expected_users',
    path: 'solutions',
    section: 'context',
    label: 'Utilisateurs concernés',
    prompt: 'Qui utilisera la solution et à quelle échelle ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 500 },
    nextStep: 'solutions.timeframe',
  }),
  defineQuestion({
    id: 'solutions.timeframe',
    path: 'solutions',
    section: 'constraints',
    label: 'Délai envisagé',
    prompt: 'Quel délai envisagez-vous ?',
    answerType: 'single_choice',
    required: true,
    options: options([
      'Dès que le cadrage est validé',
      'Sous un mois',
      'Sous trois mois',
      'Sous six mois',
      'À définir',
    ]),
    nextStep: 'solutions.budget_range',
  }),
  defineQuestion({
    id: 'solutions.budget_range',
    path: 'solutions',
    section: 'constraints',
    label: 'Enveloppe indicative',
    prompt: 'Souhaitez-vous indiquer une enveloppe de travail ?',
    helpText: 'Facultatif ; son absence ne disqualifie pas le projet.',
    answerType: 'single_choice',
    required: false,
    options: indicativeBudgetOptions,
    nextStep: 'solutions.constraints',
  }),
  defineQuestion({
    id: 'solutions.constraints',
    path: 'solutions',
    section: 'constraints',
    label: 'Contraintes importantes',
    prompt: 'Quelles contraintes techniques, métier ou réglementaires faut-il connaître ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1500 },
    nextStep: 'solutions.data_sensitivity',
    allowsFreeText: true,
  }),
  defineQuestion({
    id: 'solutions.data_sensitivity',
    path: 'solutions',
    section: 'constraints',
    label: 'Sensibilité des données',
    prompt: 'Le projet concerne-t-il des données sensibles ou réglementées ?',
    answerType: 'single_choice',
    required: true,
    options: options([
      'Non',
      'Oui, données personnelles',
      'Oui, données métier confidentielles',
      'Oui, données réglementées',
      'À déterminer',
    ]),
    nextStep: 'solutions.human_review_need',
    humanReviewTrigger: {
      reason: 'La sensibilité des données doit être confirmée humainement.',
      severity: 'review',
      condition: {
        questionId: 'solutions.data_sensitivity',
        operator: 'not_equals',
        value: 'Non',
      },
    },
  }),
  defineQuestion({
    id: 'solutions.human_review_need',
    path: 'solutions',
    section: 'constraints',
    label: 'Validation humaine ou technique',
    prompt: 'Quels points nécessitent une validation humaine ou technique ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: solutionBranchEntry,
    allowsFreeText: true,
    humanReviewTrigger: {
      reason: 'Le visiteur a identifié un point à valider.',
      severity: 'review',
      condition: {
        questionId: 'solutions.human_review_need',
        operator: 'exists',
      },
    },
  }),
] as const satisfies readonly ConciergeStep[]

type BranchQuestionInput = Omit<QuestionInput, 'path' | 'condition'> & {
  category: string
}

function branchQuestion(input: BranchQuestionInput): ConciergeQuestion {
  const { category, ...question } = input
  return defineQuestion({
    ...question,
    path: 'solutions',
    condition: categoryCondition(category),
  })
}

const solutionBranchSteps = [
  branchQuestion({
    id: 'solutions.website_seo_geo.start',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Création ou refonte',
    prompt: 'S’agit-il d’une création ou d’une refonte ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Création', 'Refonte', 'Évolution ciblée', 'À déterminer']),
    nextStep: 'solutions.website_seo_geo.objectives',
  }),
  branchQuestion({
    id: 'solutions.website_seo_geo.objectives',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Objectifs principaux',
    prompt: 'Quels sont les objectifs principaux du site ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1200 },
    nextStep: 'solutions.website_seo_geo.current_site',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.website_seo_geo.current_site',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Site actuel',
    prompt: 'Que faut-il conserver ou corriger sur le site actuel ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.website_seo_geo.features',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.website_seo_geo.features',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Fonctionnalités attendues',
    prompt: 'Quelles fonctionnalités sont nécessaires ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1200 },
    nextStep: 'solutions.website_seo_geo.markets',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.website_seo_geo.markets',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Zones ou marchés',
    prompt: 'Quelles zones ou quels marchés le site doit-il cibler ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 500 },
    nextStep: 'solutions.website_seo_geo.content',
  }),
  branchQuestion({
    id: 'solutions.website_seo_geo.content',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Contenus disponibles',
    prompt: 'Quels contenus et éléments de marque sont déjà disponibles ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1000 },
    nextStep: 'solutions.website_seo_geo.seo_need',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.website_seo_geo.seo_need',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Besoin SEO',
    prompt: 'Quel besoin SEO avez-vous identifié ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1000 },
    nextStep: 'solutions.website_seo_geo.geo_need',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.website_seo_geo.geo_need',
    category: 'website_seo_geo',
    section: 'website_seo_geo',
    label: 'Besoin GEO',
    prompt: 'Souhaitez-vous travailler la visibilité dans les moteurs génératifs ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1000 },
    nextStep: 'summary.review',
    allowsFreeText: true,
  }),

  branchQuestion({
    id: 'solutions.business_software.start',
    category: 'business_software',
    section: 'business_software',
    label: 'Processus concerné',
    prompt: 'Quel processus métier doit être outillé ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 10, maxLength: 1500 },
    nextStep: 'solutions.business_software.users',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.business_software.users',
    category: 'business_software',
    section: 'business_software',
    label: 'Profils utilisateurs',
    prompt: 'Quels profils utiliseront le logiciel ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 500 },
    nextStep: 'solutions.business_software.rules',
  }),
  branchQuestion({
    id: 'solutions.business_software.rules',
    category: 'business_software',
    section: 'business_software',
    label: 'Règles métier',
    prompt: 'Quelles règles métier structurent ce processus ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 10, maxLength: 1800 },
    nextStep: 'solutions.business_software.current_tools',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.business_software.current_tools',
    category: 'business_software',
    section: 'business_software',
    label: 'Outils actuels',
    prompt: 'Quels outils utilisez-vous actuellement ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.business_software.integrations',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.business_software.integrations',
    category: 'business_software',
    section: 'business_software',
    label: 'Intégrations',
    prompt: 'Quels systèmes devront être intégrés ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.business_software.data_migration',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.business_software.data_migration',
    category: 'business_software',
    section: 'business_software',
    label: 'Données à migrer',
    prompt: 'Existe-t-il des données à reprendre ou à migrer ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.business_software.access_rights',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.business_software.access_rights',
    category: 'business_software',
    section: 'business_software',
    label: 'Droits d’accès',
    prompt: 'Quels rôles ou droits d’accès faut-il prévoir ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1000 },
    nextStep: 'solutions.business_software.criticality',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.business_software.criticality',
    category: 'business_software',
    section: 'business_software',
    label: 'Criticité opérationnelle',
    prompt: 'Quel serait l’impact d’une indisponibilité du logiciel ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1000 },
    nextStep: 'summary.review',
    allowsFreeText: true,
    humanReviewTrigger: {
      reason: 'La criticité opérationnelle doit être validée techniquement.',
      severity: 'review',
    },
  }),

  branchQuestion({
    id: 'solutions.web_app_integration.start',
    category: 'web_app_integration',
    section: 'web_app_integration',
    label: 'Systèmes à connecter',
    prompt: 'Quels systèmes doivent être connectés ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1500 },
    nextStep: 'solutions.web_app_integration.manual_tasks',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.web_app_integration.manual_tasks',
    category: 'web_app_integration',
    section: 'web_app_integration',
    label: 'Tâches manuelles',
    prompt: 'Quelles tâches manuelles souhaitez-vous réduire ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1500 },
    nextStep: 'solutions.web_app_integration.triggers',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.web_app_integration.triggers',
    category: 'web_app_integration',
    section: 'web_app_integration',
    label: 'Déclencheurs',
    prompt: 'Quels événements doivent déclencher les traitements ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1200 },
    nextStep: 'solutions.web_app_integration.volumes',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.web_app_integration.volumes',
    category: 'web_app_integration',
    section: 'web_app_integration',
    label: 'Volumes',
    prompt: 'Quels volumes et quelles fréquences faut-il traiter ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 500 },
    nextStep: 'solutions.web_app_integration.apis',
  }),
  branchQuestion({
    id: 'solutions.web_app_integration.apis',
    category: 'web_app_integration',
    section: 'web_app_integration',
    label: 'API disponibles',
    prompt: 'Les systèmes disposent-ils d’API documentées ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Oui', 'Partiellement', 'Non', 'À vérifier']),
    nextStep: 'solutions.web_app_integration.expected_result',
  }),
  branchQuestion({
    id: 'solutions.web_app_integration.expected_result',
    category: 'web_app_integration',
    section: 'web_app_integration',
    label: 'Résultat attendu',
    prompt: 'Quel résultat concret attendez-vous ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1200 },
    nextStep: 'solutions.web_app_integration.error_tolerance',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.web_app_integration.error_tolerance',
    category: 'web_app_integration',
    section: 'web_app_integration',
    label: 'Tolérance aux erreurs',
    prompt: 'Quelle tolérance aux erreurs ou aux retards est acceptable ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1000 },
    nextStep: 'summary.review',
    allowsFreeText: true,
    humanReviewTrigger: {
      reason: 'Les exigences de reprise sur erreur doivent être validées.',
      severity: 'review',
    },
  }),

  branchQuestion({
    id: 'solutions.local_ai.start',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Cas d’usage',
    prompt: 'Quel cas d’usage d’IA locale souhaitez-vous couvrir ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 10, maxLength: 1500 },
    nextStep: 'solutions.local_ai.data_types',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.local_ai.data_types',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Types de données',
    prompt: 'Quels types de données seront traités ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1200 },
    nextStep: 'solutions.local_ai.confidentiality',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.local_ai.confidentiality',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Niveau de confidentialité',
    prompt: 'Quel niveau de confidentialité est requis ?',
    answerType: 'single_choice',
    required: true,
    options: options([
      'Standard',
      'Confidentiel entreprise',
      'Très sensible',
      'Réglementé',
      'À déterminer',
    ]),
    nextStep: 'solutions.local_ai.current_models',
    humanReviewTrigger: {
      reason: 'Le niveau de confidentialité doit être confirmé.',
      severity: 'review',
      condition: {
        questionId: 'solutions.local_ai.confidentiality',
        operator: 'not_equals',
        value: 'Standard',
      },
    },
  }),
  branchQuestion({
    id: 'solutions.local_ai.current_models',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Modèles ou outils actuels',
    prompt: 'Quels modèles ou outils utilisez-vous déjà ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.local_ai.user_count',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.local_ai.user_count',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Nombre d’utilisateurs',
    prompt: 'Combien d’utilisateurs sont concernés ?',
    answerType: 'number',
    required: true,
    validation: { min: 1, max: 1000000, format: 'integer' },
    nextStep: 'solutions.local_ai.latency',
  }),
  branchQuestion({
    id: 'solutions.local_ai.latency',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Latence attendue',
    prompt: 'Quel niveau de réactivité est attendu ?',
    answerType: 'short_text',
    required: false,
    validation: { maxLength: 400 },
    nextStep: 'solutions.local_ai.environment',
  }),
  branchQuestion({
    id: 'solutions.local_ai.environment',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Environnement disponible',
    prompt: 'Quel environnement matériel et logiciel est disponible ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.local_ai.offline',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.local_ai.offline',
    category: 'local_ai',
    section: 'local_ai',
    label: 'Exigences hors ligne',
    prompt: 'Le système doit-il fonctionner sans accès internet ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Oui', 'Non', 'Partiellement', 'À déterminer']),
    nextStep: 'summary.review',
  }),

  branchQuestion({
    id: 'solutions.ai_infrastructure.start',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Modèles envisagés',
    prompt: 'Quels modèles ou familles de modèles envisagez-vous ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.ai_infrastructure.concurrent_users',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.ai_infrastructure.concurrent_users',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Utilisateurs simultanés',
    prompt: 'Combien d’utilisateurs simultanés faut-il prévoir ?',
    answerType: 'number',
    required: true,
    validation: { min: 1, max: 1000000, format: 'integer' },
    nextStep: 'solutions.ai_infrastructure.model_size',
  }),
  branchQuestion({
    id: 'solutions.ai_infrastructure.model_size',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Taille des modèles',
    prompt: 'Quelles tailles de modèles doivent être prises en charge ?',
    answerType: 'short_text',
    required: false,
    validation: { maxLength: 400 },
    nextStep: 'solutions.ai_infrastructure.workload',
  }),
  branchQuestion({
    id: 'solutions.ai_infrastructure.workload',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Type de charge',
    prompt: 'S’agit-il principalement d’inférence, d’entraînement ou des deux ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Inférence', 'Entraînement', 'Les deux', 'À déterminer']),
    nextStep: 'solutions.ai_infrastructure.availability',
  }),
  branchQuestion({
    id: 'solutions.ai_infrastructure.availability',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Disponibilité attendue',
    prompt: 'Quel niveau de disponibilité est attendu ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 500 },
    nextStep: 'solutions.ai_infrastructure.power_noise',
  }),
  branchQuestion({
    id: 'solutions.ai_infrastructure.power_noise',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Consommation et bruit',
    prompt: 'Quelles contraintes de consommation et de bruit sont acceptables ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1000 },
    nextStep: 'solutions.ai_infrastructure.technical_room',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.ai_infrastructure.technical_room',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Local technique',
    prompt: 'Un local technique adapté est-il disponible ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Oui', 'Non', 'À vérifier', 'Non nécessaire pour une station']),
    nextStep: 'solutions.ai_infrastructure.budget',
  }),
  branchQuestion({
    id: 'solutions.ai_infrastructure.budget',
    category: 'ai_infrastructure',
    section: 'ai_infrastructure',
    label: 'Budget indicatif matériel',
    prompt: 'Quelle enveloppe matérielle indicative envisagez-vous ?',
    answerType: 'single_choice',
    required: false,
    options: indicativeBudgetOptions,
    nextStep: 'summary.review',
  }),

  branchQuestion({
    id: 'solutions.backup_continuity.start',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Données à protéger',
    prompt: 'Quelles données et quels systèmes doivent être protégés ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1500 },
    nextStep: 'solutions.backup_continuity.volume',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.backup_continuity.volume',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Volumétrie',
    prompt: 'Quelle volumétrie faut-il protéger aujourd’hui et demain ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 500 },
    nextStep: 'solutions.backup_continuity.current_equipment',
  }),
  branchQuestion({
    id: 'solutions.backup_continuity.current_equipment',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Équipements actuels',
    prompt: 'Quels équipements ou services de sauvegarde utilisez-vous ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1200 },
    nextStep: 'solutions.backup_continuity.frequency',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.backup_continuity.frequency',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Fréquence',
    prompt: 'Quelle fréquence de sauvegarde est nécessaire ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 400 },
    nextStep: 'solutions.backup_continuity.offsite',
  }),
  branchQuestion({
    id: 'solutions.backup_continuity.offsite',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Copie hors site',
    prompt: 'Une copie hors site est-elle prévue ou souhaitée ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Oui', 'Non', 'Déjà en place', 'À étudier']),
    nextStep: 'solutions.backup_continuity.encryption',
  }),
  branchQuestion({
    id: 'solutions.backup_continuity.encryption',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Chiffrement',
    prompt: 'Quelles exigences de chiffrement s’appliquent ?',
    answerType: 'long_text',
    required: false,
    validation: { maxLength: 1000 },
    nextStep: 'solutions.backup_continuity.restore_tests',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.backup_continuity.restore_tests',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Tests de restauration',
    prompt: 'À quelle fréquence les restaurations doivent-elles être testées ?',
    answerType: 'short_text',
    required: true,
    validation: { minLength: 2, maxLength: 400 },
    nextStep: 'solutions.backup_continuity.criticality',
  }),
  branchQuestion({
    id: 'solutions.backup_continuity.criticality',
    category: 'backup_continuity',
    section: 'backup_continuity',
    label: 'Criticité',
    prompt: 'Quel serait l’impact d’une perte ou indisponibilité des données ?',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1200 },
    nextStep: 'summary.review',
    allowsFreeText: true,
    humanReviewTrigger: {
      reason: 'Les objectifs de continuité doivent être validés techniquement.',
      severity: 'review',
    },
  }),

  branchQuestion({
    id: 'solutions.cybersecurity_authorized_audit.start',
    category: 'cybersecurity_authorized_audit',
    section: 'cybersecurity_authorized_audit',
    label: 'Type de cible',
    prompt: 'Quel type de système souhaitez-vous faire qualifier ?',
    helpText:
      'Le concierge ne réalise aucune action active et sert uniquement au cadrage initial.',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1000 },
    nextStep: 'solutions.cybersecurity_authorized_audit.authorization',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.cybersecurity_authorized_audit.authorization',
    category: 'cybersecurity_authorized_audit',
    section: 'cybersecurity_authorized_audit',
    label: 'Propriété ou autorisation',
    prompt: 'Disposez-vous d’une autorisation écrite ou maîtrisez-vous juridiquement la cible ?',
    helpText:
      'Une autorisation écrite et un périmètre en liste blanche sont obligatoires avant tout audit actif.',
    answerType: 'single_choice',
    required: true,
    options: [
      {
        value: 'written_authorization_available',
        label: 'Autorisation écrite disponible',
      },
      { value: 'target_owner', label: 'Nous sommes propriétaires de la cible' },
      { value: 'not_yet', label: 'Autorisation pas encore obtenue' },
      { value: 'unknown', label: 'À confirmer' },
    ],
    validation: { customRule: 'written_authorization_required' },
    nextStep: 'solutions.cybersecurity_authorized_audit.scope',
    humanReviewTrigger: {
      reason:
        'Sans autorisation écrite vérifiée, la demande reste bloquée au stade de qualification.',
      severity: 'blocking',
      condition: {
        questionId: 'solutions.cybersecurity_authorized_audit.authorization',
        operator: 'one_of',
        value: ['not_yet', 'unknown'],
      },
    },
  }),
  branchQuestion({
    id: 'solutions.cybersecurity_authorized_audit.scope',
    category: 'cybersecurity_authorized_audit',
    section: 'cybersecurity_authorized_audit',
    label: 'Périmètre général',
    prompt: 'Quel périmètre général peut être placé en liste blanche ?',
    helpText: 'Aucun test hors périmètre n’est autorisé.',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1500 },
    nextStep: 'solutions.cybersecurity_authorized_audit.objective',
    allowsFreeText: true,
    sensitiveData: true,
    sensitiveDataJustification:
      'Le périmètre est indispensable pour vérifier l’autorisation et limiter la qualification.',
  }),
  branchQuestion({
    id: 'solutions.cybersecurity_authorized_audit.objective',
    category: 'cybersecurity_authorized_audit',
    section: 'cybersecurity_authorized_audit',
    label: 'Objectif',
    prompt: 'Quel est l’objectif de l’audit ?',
    helpText: 'Aucune certification ni absence de vulnérabilité ne peut être promise.',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 5, maxLength: 1200 },
    nextStep: 'solutions.cybersecurity_authorized_audit.sensitivity',
    allowsFreeText: true,
  }),
  branchQuestion({
    id: 'solutions.cybersecurity_authorized_audit.sensitivity',
    category: 'cybersecurity_authorized_audit',
    section: 'cybersecurity_authorized_audit',
    label: 'Sensibilité',
    prompt: 'Quel niveau de sensibilité présente l’environnement ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Standard', 'Sensible', 'Critique', 'Réglementé', 'À déterminer']),
    nextStep: 'solutions.cybersecurity_authorized_audit.test_environment',
    humanReviewTrigger: {
      reason: 'Toute demande cybersécurité nécessite une revue humaine.',
      severity: 'review',
    },
  }),
  branchQuestion({
    id: 'solutions.cybersecurity_authorized_audit.test_environment',
    category: 'cybersecurity_authorized_audit',
    section: 'cybersecurity_authorized_audit',
    label: 'Environnement de test',
    prompt: 'Un environnement de test représentatif est-il disponible ?',
    answerType: 'single_choice',
    required: true,
    options: options(['Oui', 'Non', 'Partiellement', 'À confirmer']),
    nextStep: 'solutions.cybersecurity_authorized_audit.audit_type',
  }),
  branchQuestion({
    id: 'solutions.cybersecurity_authorized_audit.audit_type',
    category: 'cybersecurity_authorized_audit',
    section: 'cybersecurity_authorized_audit',
    label: 'Type de qualification',
    prompt: 'Quel type d’intervention envisagez-vous ?',
    answerType: 'single_choice',
    required: true,
    options: [
      { value: 'public_pre_audit', label: 'Pré-audit de données publiques' },
      {
        value: 'authorized_full_audit',
        label: 'Audit autorisé complet à cadrer',
      },
      { value: 'unknown', label: 'À déterminer avec Novekia' },
    ],
    nextStep: 'summary.review',
    humanReviewTrigger: {
      reason:
        'La portée, la preuve de maîtrise et l’autorisation doivent être vérifiées avant toute action.',
      severity: 'blocking',
    },
  }),

  branchQuestion({
    id: 'solutions.other.start',
    category: 'other',
    section: 'other',
    label: 'Autre besoin',
    prompt: 'Décrivez le besoin qui ne correspond pas aux catégories proposées.',
    answerType: 'long_text',
    required: true,
    validation: { minLength: 20, maxLength: 2000 },
    nextStep: 'summary.review',
    allowsFreeText: true,
    humanReviewTrigger: {
      reason: 'Un besoin hors catégories doit être orienté humainement.',
      severity: 'review',
    },
  }),
] as const satisfies readonly ConciergeStep[]

export const leadEngineFlow: ConciergeFlowDefinition = {
  id: 'flow.lead_engine.v1',
  path: 'lead_engine',
  label: 'Développer ma prospection',
  description:
    'Qualification d’un besoin de prospection et de développement commercial B2B.',
  startStepId: 'lead.company_name',
  exitStepId: 'submission.ready',
  steps: leadEngineSteps,
}

export const solutionsFlow: ConciergeFlowDefinition = {
  id: 'flow.solutions.v1',
  path: 'solutions',
  label: 'Réaliser un projet numérique',
  description:
    'Qualification commune puis branche spécialisée selon la catégorie du besoin.',
  startStepId: 'solutions.company_name',
  exitStepId: 'submission.ready',
  steps: [...solutionCommonSteps, ...solutionBranchSteps],
}

export const informationFlow: ConciergeFlowDefinition = {
  id: 'flow.information.v1',
  path: 'information',
  label: 'Comprendre les services Novekia',
  description:
    'Orientation initiale vers le bon pôle avant une éventuelle demande de contact.',
  startStepId: 'information.topic',
  exitStepId: 'submission.ready',
  steps: [
    defineQuestion({
      id: 'information.topic',
      path: 'information',
      section: 'orientation',
      label: 'Sujet à comprendre',
      prompt: 'Quel sujet souhaitez-vous mieux comprendre ?',
      answerType: 'single_choice',
      required: true,
      options: options([
        'Lead Engine Studio',
        'Novekia Solutions',
        'Méthode et fonctionnement',
        'Sécurité et souveraineté',
        'Autre',
      ]),
      nextStep: 'summary.review',
      allowsFreeText: true,
    }),
  ],
}

export const directContactFlow: ConciergeFlowDefinition = {
  id: 'flow.direct_contact.v1',
  path: 'direct_contact',
  label: 'Contacter directement Novekia',
  description:
    'Prépare un motif de contact minimal et une synthèse avant la collecte des coordonnées.',
  startStepId: 'direct_contact.reason',
  exitStepId: 'submission.ready',
  steps: [
    defineQuestion({
      id: 'direct_contact.reason',
      path: 'direct_contact',
      section: 'orientation',
      label: 'Motif du contact',
      prompt: 'En quelques mots, quel est l’objectif de votre prise de contact ?',
      answerType: 'long_text',
      required: true,
      validation: { minLength: 10, maxLength: 1500 },
      nextStep: 'summary.review',
      allowsFreeText: true,
    }),
  ],
}

export const conciergeDefinition: ConciergeDefinition = {
  assistantName: 'Assistant Novekia',
  schemaVersion: CONCIERGE_SCHEMA_VERSION,
  openingMessage:
    'Parlons de votre objectif. En quelques questions, je peux vous orienter vers le pôle Novekia le plus pertinent et préparer un premier cadrage.',
  initialChoices: [
    {
      id: 'initial.lead_engine',
      label: 'Développer ma prospection',
      path: 'lead_engine',
      startStepId: leadEngineFlow.startStepId,
    },
    {
      id: 'initial.solutions',
      label: 'Réaliser un projet numérique',
      path: 'solutions',
      startStepId: solutionsFlow.startStepId,
    },
    {
      id: 'initial.information',
      label: 'Comprendre les services Novekia',
      path: 'information',
      startStepId: informationFlow.startStepId,
    },
    {
      id: 'initial.direct_contact',
      label: 'Contacter directement Novekia',
      path: 'direct_contact',
      startStepId: directContactFlow.startStepId,
    },
  ],
  sharedSteps: sharedConciergeSteps,
  flows: [leadEngineFlow, solutionsFlow, informationFlow, directContactFlow],
}

export function getFlowByPath(
  path: ConciergePath,
  definition: ConciergeDefinition = conciergeDefinition,
): ConciergeFlowDefinition | undefined {
  return definition.flows.find((flow) => flow.path === path)
}

export function getAllStepsForFlow(
  flow: ConciergeFlowDefinition,
  definition: ConciergeDefinition = conciergeDefinition,
): readonly ConciergeStep[] {
  return [...flow.steps, ...definition.sharedSteps]
}

export function getStepById(
  flow: ConciergeFlowDefinition,
  stepId: string,
  definition: ConciergeDefinition = conciergeDefinition,
): ConciergeStep | undefined {
  return getAllStepsForFlow(flow, definition).find((step) => step.id === stepId)
}
